jQuery.extend(jQuery.validator.messages, {
  required: "此项不能为空",
  remote: "请修正该字段",
  email: "请输入正确格式的电子邮件",
  url: "请输入合法的网址",
  date: "请输入合法的日期",
  dateISO: "请输入合法的日期 (ISO).",
  time:"时间格式不正确",
  number: "请输入合法的数字",
  onlyNumber:"只可输入数字",
  digits: "只能输入整数",
  creditcard: "请输入合法的信用卡号",
  equalTo: "密码不一致",
  accept: "请输入拥有合法后缀名的字符串",
  phone:"请输入有效的手机号",
  decimal:"最多只可保留两位小数",
  positive:"请输入大于0的正整数",
  length:"输入长度只能是{0}位",
  mobilePhone:"请输入有效的固定电话或手机号,如：0591-6487256，15005059587",
  maxlength: jQuery.validator.format("请输入一个 长度最多是 {0} 的字符串"),
  minlength: jQuery.validator.format("请输入一个 长度最少是 {0} 的字符串"),
  rangelength: jQuery.validator.format("此项要求 {0} - {1} 个字符"),
  range: jQuery.validator.format("请输入一个介于 {0} 和 {1} 之间的值"),
  max: jQuery.validator.format("请输入一个最大为{0} 的值"),
  zh_CN:jQuery.validator.format("此项只允许输入中文"),
  min: jQuery.validator.format("请输入一个最小为{0} 的值")
});
